/run/initialize
/gun/particle gamma

/gun/energy 120 keV
/run/baemOn 10

/gun/energy 121 keV
/run/baemOn 10

/gun/energy 122 keV
/run/baemOn 10

/gun/energy 123 keV
/run/baemOn 10

/gun/energy 124 keV
/run/baemOn 10

/gun/energy 125 keV
/run/baemOn 10

/gun/energy 126 keV
/run/baemOn 10

/gun/energy 127 keV
/run/baemOn 10

/gun/energy 128 keV
/run/baemOn 10

/gun/energy 129 keV
/run/baemOn 10

/gun/energy 130 keV
/run/baemOn 10

/gun/energy 131 keV
/run/baemOn 10

/gun/energy 132 keV
/run/baemOn 10

/gun/energy 133 keV
/run/baemOn 10

/gun/energy 134 keV
/run/baemOn 10

/gun/energy 135 keV
/run/baemOn 10

/gun/energy 136 keV
/run/baemOn 10

/gun/energy 137 keV
/run/baemOn 10

/gun/energy 138 keV
/run/baemOn 10

/gun/energy 139 keV
/run/baemOn 10

/gun/energy 140 keV
/run/baemOn 10

/gun/energy 141 keV
/run/baemOn 10

/gun/energy 142 keV
/run/baemOn 10

/gun/energy 143 keV
/run/baemOn 10

/gun/energy 144 keV
/run/baemOn 10

/gun/energy 145 keV
/run/baemOn 10

/gun/energy 146 keV
/run/baemOn 10

/gun/energy 147 keV
/run/baemOn 10

/gun/energy 148 keV
/run/baemOn 10

/gun/energy 149 keV
/run/baemOn 10

/gun/energy 150 keV
/run/baemOn 10

/gun/energy 151 keV
/run/baemOn 10

/gun/energy 152 keV
/run/baemOn 10

/gun/energy 153 keV
/run/baemOn 10

/gun/energy 154 keV
/run/baemOn 10

/gun/energy 155 keV
/run/baemOn 10

/gun/energy 156 keV
/run/baemOn 10

/gun/energy 157 keV
/run/baemOn 10

/gun/energy 158 keV
/run/baemOn 10

/gun/energy 159 keV
/run/baemOn 10

/gun/energy 160 keV
/run/baemOn 10

/gun/energy 161 keV
/run/baemOn 10

/gun/energy 162 keV
/run/baemOn 10

/gun/energy 163 keV
/run/baemOn 10

/gun/energy 164 keV
/run/baemOn 10

/gun/energy 165 keV
/run/baemOn 10

/gun/energy 166 keV
/run/baemOn 10

/gun/energy 167 keV
/run/baemOn 10

/gun/energy 168 keV
/run/baemOn 10

/gun/energy 169 keV
/run/baemOn 10

/gun/energy 170 keV
/run/baemOn 10

/gun/energy 171 keV
/run/baemOn 10

/gun/energy 172 keV
/run/baemOn 10

/gun/energy 173 keV
/run/baemOn 10

/gun/energy 174 keV
/run/baemOn 10

/gun/energy 175 keV
/run/baemOn 10

/gun/energy 176 keV
/run/baemOn 10

/gun/energy 177 keV
/run/baemOn 10

/gun/energy 178 keV
/run/baemOn 10

/gun/energy 179 keV
/run/baemOn 10

/gun/energy 180 keV
/run/baemOn 10

/gun/energy 181 keV
/run/baemOn 10

/gun/energy 182 keV
/run/baemOn 10

/gun/energy 183 keV
/run/baemOn 10

/gun/energy 184 keV
/run/baemOn 10

/gun/energy 185 keV
/run/baemOn 10

/gun/energy 186 keV
/run/baemOn 10

/gun/energy 187 keV
/run/baemOn 10

/gun/energy 188 keV
/run/baemOn 10

/gun/energy 189 keV
/run/baemOn 10

/gun/energy 190 keV
/run/baemOn 10

/gun/energy 191 keV
/run/baemOn 10

/gun/energy 192 keV
/run/baemOn 10

/gun/energy 193 keV
/run/baemOn 10

/gun/energy 194 keV
/run/baemOn 10

/gun/energy 195 keV
/run/baemOn 10

/gun/energy 196 keV
/run/baemOn 10

/gun/energy 197 keV
/run/baemOn 10

/gun/energy 198 keV
/run/baemOn 10

/gun/energy 199 keV
/run/baemOn 10

/gun/energy 200 keV
/run/baemOn 10

/gun/energy 201 keV
/run/baemOn 10

/gun/energy 202 keV
/run/baemOn 10

/gun/energy 203 keV
/run/baemOn 10

/gun/energy 204 keV
/run/baemOn 10

/gun/energy 205 keV
/run/baemOn 10

/gun/energy 206 keV
/run/baemOn 10

/gun/energy 207 keV
/run/baemOn 10

/gun/energy 208 keV
/run/baemOn 10

/gun/energy 209 keV
/run/baemOn 10

/gun/energy 210 keV
/run/baemOn 10

/gun/energy 211 keV
/run/baemOn 10

/gun/energy 212 keV
/run/baemOn 10

/gun/energy 213 keV
/run/baemOn 10

/gun/energy 214 keV
/run/baemOn 10

/gun/energy 215 keV
/run/baemOn 10

/gun/energy 216 keV
/run/baemOn 10

/gun/energy 217 keV
/run/baemOn 10

/gun/energy 218 keV
/run/baemOn 10

/gun/energy 219 keV
/run/baemOn 10

/gun/energy 220 keV
/run/baemOn 10

/gun/energy 221 keV
/run/baemOn 10

/gun/energy 222 keV
/run/baemOn 10

/gun/energy 223 keV
/run/baemOn 10

/gun/energy 224 keV
/run/baemOn 10

/gun/energy 225 keV
/run/baemOn 10

/gun/energy 226 keV
/run/baemOn 10

/gun/energy 227 keV
/run/baemOn 10

/gun/energy 228 keV
/run/baemOn 10

/gun/energy 229 keV
/run/baemOn 10

/gun/energy 230 keV
/run/baemOn 10

/gun/energy 231 keV
/run/baemOn 10

/gun/energy 232 keV
/run/baemOn 10

/gun/energy 233 keV
/run/baemOn 10

/gun/energy 234 keV
/run/baemOn 10

/gun/energy 235 keV
/run/baemOn 10

/gun/energy 236 keV
/run/baemOn 10

/gun/energy 237 keV
/run/baemOn 10

/gun/energy 238 keV
/run/baemOn 10

/gun/energy 239 keV
/run/baemOn 10

/gun/energy 240 keV
/run/baemOn 10

/gun/energy 241 keV
/run/baemOn 10

/gun/energy 242 keV
/run/baemOn 10

/gun/energy 243 keV
/run/baemOn 10

/gun/energy 244 keV
/run/baemOn 10

/gun/energy 245 keV
/run/baemOn 10

/gun/energy 246 keV
/run/baemOn 10

/gun/energy 247 keV
/run/baemOn 10

/gun/energy 248 keV
/run/baemOn 10

/gun/energy 249 keV
/run/baemOn 10

/gun/energy 250 keV
/run/baemOn 10

/gun/energy 251 keV
/run/baemOn 10

/gun/energy 252 keV
/run/baemOn 10

/gun/energy 253 keV
/run/baemOn 10

/gun/energy 254 keV
/run/baemOn 10

/gun/energy 255 keV
/run/baemOn 10

/gun/energy 256 keV
/run/baemOn 10

/gun/energy 257 keV
/run/baemOn 10

/gun/energy 258 keV
/run/baemOn 10

/gun/energy 259 keV
/run/baemOn 10

/gun/energy 260 keV
/run/baemOn 10

/gun/energy 261 keV
/run/baemOn 10

/gun/energy 262 keV
/run/baemOn 10

/gun/energy 263 keV
/run/baemOn 10

/gun/energy 264 keV
/run/baemOn 10

/gun/energy 265 keV
/run/baemOn 10

/gun/energy 266 keV
/run/baemOn 10

/gun/energy 267 keV
/run/baemOn 10

/gun/energy 268 keV
/run/baemOn 10

/gun/energy 269 keV
/run/baemOn 10

/gun/energy 270 keV
/run/baemOn 10

/gun/energy 271 keV
/run/baemOn 10

/gun/energy 272 keV
/run/baemOn 10

/gun/energy 273 keV
/run/baemOn 10

/gun/energy 274 keV
/run/baemOn 10

/gun/energy 275 keV
/run/baemOn 10

/gun/energy 276 keV
/run/baemOn 10

/gun/energy 277 keV
/run/baemOn 10

/gun/energy 278 keV
/run/baemOn 10

/gun/energy 279 keV
/run/baemOn 10

/gun/energy 280 keV
/run/baemOn 10

/gun/energy 281 keV
/run/baemOn 10

/gun/energy 282 keV
/run/baemOn 10

/gun/energy 283 keV
/run/baemOn 10

/gun/energy 284 keV
/run/baemOn 10

/gun/energy 285 keV
/run/baemOn 10

/gun/energy 286 keV
/run/baemOn 10

/gun/energy 287 keV
/run/baemOn 10

/gun/energy 288 keV
/run/baemOn 10

/gun/energy 289 keV
/run/baemOn 10

/gun/energy 290 keV
/run/baemOn 10

/gun/energy 291 keV
/run/baemOn 10

/gun/energy 292 keV
/run/baemOn 10

/gun/energy 293 keV
/run/baemOn 10

/gun/energy 294 keV
/run/baemOn 10

/gun/energy 295 keV
/run/baemOn 10

/gun/energy 296 keV
/run/baemOn 10

/gun/energy 297 keV
/run/baemOn 10

/gun/energy 298 keV
/run/baemOn 10

/gun/energy 299 keV
/run/baemOn 10

/gun/energy 300 keV
/run/baemOn 10

/gun/energy 301 keV
/run/baemOn 10

/gun/energy 302 keV
/run/baemOn 10

/gun/energy 303 keV
/run/baemOn 10

/gun/energy 304 keV
/run/baemOn 10

/gun/energy 305 keV
/run/baemOn 10

/gun/energy 306 keV
/run/baemOn 10

/gun/energy 307 keV
/run/baemOn 10

/gun/energy 308 keV
/run/baemOn 10

/gun/energy 309 keV
/run/baemOn 10

/gun/energy 310 keV
/run/baemOn 10

/gun/energy 311 keV
/run/baemOn 10

/gun/energy 312 keV
/run/baemOn 10

/gun/energy 313 keV
/run/baemOn 10

/gun/energy 314 keV
/run/baemOn 10

/gun/energy 315 keV
/run/baemOn 10

/gun/energy 316 keV
/run/baemOn 10

/gun/energy 317 keV
/run/baemOn 10

/gun/energy 318 keV
/run/baemOn 10

/gun/energy 319 keV
/run/baemOn 10

/gun/energy 320 keV
/run/baemOn 10

/gun/energy 321 keV
/run/baemOn 10

/gun/energy 322 keV
/run/baemOn 10

/gun/energy 323 keV
/run/baemOn 10

/gun/energy 324 keV
/run/baemOn 10

/gun/energy 325 keV
/run/baemOn 10

/gun/energy 326 keV
/run/baemOn 10

/gun/energy 327 keV
/run/baemOn 10

/gun/energy 328 keV
/run/baemOn 10

/gun/energy 329 keV
/run/baemOn 10

/gun/energy 330 keV
/run/baemOn 10

/gun/energy 331 keV
/run/baemOn 10

/gun/energy 332 keV
/run/baemOn 10

/gun/energy 333 keV
/run/baemOn 10

/gun/energy 334 keV
/run/baemOn 10

/gun/energy 335 keV
/run/baemOn 10

/gun/energy 336 keV
/run/baemOn 10

/gun/energy 337 keV
/run/baemOn 10

/gun/energy 338 keV
/run/baemOn 10

/gun/energy 339 keV
/run/baemOn 10

/gun/energy 340 keV
/run/baemOn 10

/gun/energy 341 keV
/run/baemOn 10

/gun/energy 342 keV
/run/baemOn 10

/gun/energy 343 keV
/run/baemOn 10

/gun/energy 344 keV
/run/baemOn 10

/gun/energy 345 keV
/run/baemOn 10

/gun/energy 346 keV
/run/baemOn 10

/gun/energy 347 keV
/run/baemOn 10

/gun/energy 348 keV
/run/baemOn 10

/gun/energy 349 keV
/run/baemOn 10

/gun/energy 350 keV
/run/baemOn 10

/gun/energy 351 keV
/run/baemOn 10

/gun/energy 352 keV
/run/baemOn 10

/gun/energy 353 keV
/run/baemOn 10

/gun/energy 354 keV
/run/baemOn 10

/gun/energy 355 keV
/run/baemOn 10

/gun/energy 356 keV
/run/baemOn 10

/gun/energy 357 keV
/run/baemOn 10

/gun/energy 358 keV
/run/baemOn 10

/gun/energy 359 keV
/run/baemOn 10

/gun/energy 360 keV
/run/baemOn 10

/gun/energy 361 keV
/run/baemOn 10

/gun/energy 362 keV
/run/baemOn 10

/gun/energy 363 keV
/run/baemOn 10

/gun/energy 364 keV
/run/baemOn 10

/gun/energy 365 keV
/run/baemOn 10

/gun/energy 366 keV
/run/baemOn 10

/gun/energy 367 keV
/run/baemOn 10

/gun/energy 368 keV
/run/baemOn 10

/gun/energy 369 keV
/run/baemOn 10

/gun/energy 370 keV
/run/baemOn 10

/gun/energy 371 keV
/run/baemOn 10

/gun/energy 372 keV
/run/baemOn 10

/gun/energy 373 keV
/run/baemOn 10

/gun/energy 374 keV
/run/baemOn 10

/gun/energy 375 keV
/run/baemOn 10

/gun/energy 376 keV
/run/baemOn 10

/gun/energy 377 keV
/run/baemOn 10

/gun/energy 378 keV
/run/baemOn 10

/gun/energy 379 keV
/run/baemOn 10

/gun/energy 380 keV
/run/baemOn 10

/gun/energy 381 keV
/run/baemOn 10

/gun/energy 382 keV
/run/baemOn 10

/gun/energy 383 keV
/run/baemOn 10

/gun/energy 384 keV
/run/baemOn 10

/gun/energy 385 keV
/run/baemOn 10

/gun/energy 386 keV
/run/baemOn 10

/gun/energy 387 keV
/run/baemOn 10

/gun/energy 388 keV
/run/baemOn 10

/gun/energy 389 keV
/run/baemOn 10

/gun/energy 390 keV
/run/baemOn 10

/gun/energy 391 keV
/run/baemOn 10

/gun/energy 392 keV
/run/baemOn 10

/gun/energy 393 keV
/run/baemOn 10

/gun/energy 394 keV
/run/baemOn 10

/gun/energy 395 keV
/run/baemOn 10

/gun/energy 396 keV
/run/baemOn 10

/gun/energy 397 keV
/run/baemOn 10

/gun/energy 398 keV
/run/baemOn 10

/gun/energy 399 keV
/run/baemOn 10

/gun/energy 400 keV
/run/baemOn 10

/gun/energy 401 keV
/run/baemOn 10

/gun/energy 402 keV
/run/baemOn 10

/gun/energy 403 keV
/run/baemOn 10

/gun/energy 404 keV
/run/baemOn 10

/gun/energy 405 keV
/run/baemOn 10

/gun/energy 406 keV
/run/baemOn 10

/gun/energy 407 keV
/run/baemOn 10

/gun/energy 408 keV
/run/baemOn 10

/gun/energy 409 keV
/run/baemOn 10

/gun/energy 410 keV
/run/baemOn 10

/gun/energy 411 keV
/run/baemOn 10

/gun/energy 412 keV
/run/baemOn 10

/gun/energy 413 keV
/run/baemOn 10

/gun/energy 414 keV
/run/baemOn 10

/gun/energy 415 keV
/run/baemOn 10

/gun/energy 416 keV
/run/baemOn 10

/gun/energy 417 keV
/run/baemOn 10

/gun/energy 418 keV
/run/baemOn 10

/gun/energy 419 keV
/run/baemOn 10

/gun/energy 420 keV
/run/baemOn 10

/gun/energy 421 keV
/run/baemOn 10

/gun/energy 422 keV
/run/baemOn 10

/gun/energy 423 keV
/run/baemOn 10

/gun/energy 424 keV
/run/baemOn 10

/gun/energy 425 keV
/run/baemOn 10

/gun/energy 426 keV
/run/baemOn 10

/gun/energy 427 keV
/run/baemOn 10

/gun/energy 428 keV
/run/baemOn 10

/gun/energy 429 keV
/run/baemOn 10

/gun/energy 430 keV
/run/baemOn 10

/gun/energy 431 keV
/run/baemOn 10

/gun/energy 432 keV
/run/baemOn 10

/gun/energy 433 keV
/run/baemOn 10

/gun/energy 434 keV
/run/baemOn 10

/gun/energy 435 keV
/run/baemOn 10

/gun/energy 436 keV
/run/baemOn 10

/gun/energy 437 keV
/run/baemOn 10

/gun/energy 438 keV
/run/baemOn 10

/gun/energy 439 keV
/run/baemOn 10

/gun/energy 440 keV
/run/baemOn 10

/gun/energy 441 keV
/run/baemOn 10

/gun/energy 442 keV
/run/baemOn 10

/gun/energy 443 keV
/run/baemOn 10

/gun/energy 444 keV
/run/baemOn 10

/gun/energy 445 keV
/run/baemOn 10

/gun/energy 446 keV
/run/baemOn 10

/gun/energy 447 keV
/run/baemOn 10

/gun/energy 448 keV
/run/baemOn 10

/gun/energy 449 keV
/run/baemOn 10

/gun/energy 450 keV
/run/baemOn 10

/gun/energy 451 keV
/run/baemOn 10

/gun/energy 452 keV
/run/baemOn 10

/gun/energy 453 keV
/run/baemOn 10

/gun/energy 454 keV
/run/baemOn 10

/gun/energy 455 keV
/run/baemOn 10

/gun/energy 456 keV
/run/baemOn 10

/gun/energy 457 keV
/run/baemOn 10

/gun/energy 458 keV
/run/baemOn 10

/gun/energy 459 keV
/run/baemOn 10

/gun/energy 460 keV
/run/baemOn 10

/gun/energy 461 keV
/run/baemOn 10

/gun/energy 462 keV
/run/baemOn 10

/gun/energy 463 keV
/run/baemOn 10

/gun/energy 464 keV
/run/baemOn 10

/gun/energy 465 keV
/run/baemOn 10

/gun/energy 466 keV
/run/baemOn 10

/gun/energy 467 keV
/run/baemOn 10

/gun/energy 468 keV
/run/baemOn 10

/gun/energy 469 keV
/run/baemOn 10

/gun/energy 470 keV
/run/baemOn 10

/gun/energy 471 keV
/run/baemOn 10

/gun/energy 472 keV
/run/baemOn 10

/gun/energy 473 keV
/run/baemOn 10

/gun/energy 474 keV
/run/baemOn 10

/gun/energy 475 keV
/run/baemOn 10

/gun/energy 476 keV
/run/baemOn 10

/gun/energy 477 keV
/run/baemOn 10

/gun/energy 478 keV
/run/baemOn 10

/gun/energy 479 keV
/run/baemOn 10

/gun/energy 480 keV
/run/baemOn 10

/gun/energy 481 keV
/run/baemOn 10

/gun/energy 482 keV
/run/baemOn 10

/gun/energy 483 keV
/run/baemOn 10

/gun/energy 484 keV
/run/baemOn 10

/gun/energy 485 keV
/run/baemOn 10

/gun/energy 486 keV
/run/baemOn 10

/gun/energy 487 keV
/run/baemOn 10

/gun/energy 488 keV
/run/baemOn 10

/gun/energy 489 keV
/run/baemOn 10

/gun/energy 490 keV
/run/baemOn 10

/gun/energy 491 keV
/run/baemOn 10

/gun/energy 492 keV
/run/baemOn 10

/gun/energy 493 keV
/run/baemOn 10

/gun/energy 494 keV
/run/baemOn 10

/gun/energy 495 keV
/run/baemOn 10

/gun/energy 496 keV
/run/baemOn 10

/gun/energy 497 keV
/run/baemOn 10

/gun/energy 498 keV
/run/baemOn 10

/gun/energy 499 keV
/run/baemOn 10

/gun/energy 500 keV
/run/baemOn 10

/gun/energy 501 keV
/run/baemOn 10

/gun/energy 502 keV
/run/baemOn 10

/gun/energy 503 keV
/run/baemOn 10

/gun/energy 504 keV
/run/baemOn 10

/gun/energy 505 keV
/run/baemOn 10

/gun/energy 506 keV
/run/baemOn 10

/gun/energy 507 keV
/run/baemOn 10

/gun/energy 508 keV
/run/baemOn 10

/gun/energy 509 keV
/run/baemOn 10

/gun/energy 510 keV
/run/baemOn 10

/gun/energy 511 keV
/run/baemOn 10

/gun/energy 512 keV
/run/baemOn 10

/gun/energy 513 keV
/run/baemOn 10

/gun/energy 514 keV
/run/baemOn 10

/gun/energy 515 keV
/run/baemOn 10

/gun/energy 516 keV
/run/baemOn 10

/gun/energy 517 keV
/run/baemOn 10

/gun/energy 518 keV
/run/baemOn 10

/gun/energy 519 keV
/run/baemOn 10

/gun/energy 520 keV
/run/baemOn 10

/gun/energy 521 keV
/run/baemOn 10

/gun/energy 522 keV
/run/baemOn 10

/gun/energy 523 keV
/run/baemOn 10

/gun/energy 524 keV
/run/baemOn 10

/gun/energy 525 keV
/run/baemOn 10

/gun/energy 526 keV
/run/baemOn 10

/gun/energy 527 keV
/run/baemOn 10

/gun/energy 528 keV
/run/baemOn 10

/gun/energy 529 keV
/run/baemOn 10

/gun/energy 530 keV
/run/baemOn 10

/gun/energy 531 keV
/run/baemOn 10

/gun/energy 532 keV
/run/baemOn 10

/gun/energy 533 keV
/run/baemOn 10

/gun/energy 534 keV
/run/baemOn 10

/gun/energy 535 keV
/run/baemOn 10

/gun/energy 536 keV
/run/baemOn 10

/gun/energy 537 keV
/run/baemOn 10

/gun/energy 538 keV
/run/baemOn 10

/gun/energy 539 keV
/run/baemOn 10

/gun/energy 540 keV
/run/baemOn 10

/gun/energy 541 keV
/run/baemOn 10

/gun/energy 542 keV
/run/baemOn 10

/gun/energy 543 keV
/run/baemOn 10

/gun/energy 544 keV
/run/baemOn 10

/gun/energy 545 keV
/run/baemOn 10

/gun/energy 546 keV
/run/baemOn 10

/gun/energy 547 keV
/run/baemOn 10

/gun/energy 548 keV
/run/baemOn 10

/gun/energy 549 keV
/run/baemOn 10

/gun/energy 550 keV
/run/baemOn 10

/gun/energy 551 keV
/run/baemOn 10

/gun/energy 552 keV
/run/baemOn 10

/gun/energy 553 keV
/run/baemOn 10

/gun/energy 554 keV
/run/baemOn 10

/gun/energy 555 keV
/run/baemOn 10

/gun/energy 556 keV
/run/baemOn 10

/gun/energy 557 keV
/run/baemOn 10

/gun/energy 558 keV
/run/baemOn 10

/gun/energy 559 keV
/run/baemOn 10

/gun/energy 560 keV
/run/baemOn 10

/gun/energy 561 keV
/run/baemOn 10

/gun/energy 562 keV
/run/baemOn 10

/gun/energy 563 keV
/run/baemOn 10

/gun/energy 564 keV
/run/baemOn 10

/gun/energy 565 keV
/run/baemOn 10

/gun/energy 566 keV
/run/baemOn 10

/gun/energy 567 keV
/run/baemOn 10

/gun/energy 568 keV
/run/baemOn 10

/gun/energy 569 keV
/run/baemOn 10

/gun/energy 570 keV
/run/baemOn 10

/gun/energy 571 keV
/run/baemOn 10

/gun/energy 572 keV
/run/baemOn 10

/gun/energy 573 keV
/run/baemOn 10

/gun/energy 574 keV
/run/baemOn 10

/gun/energy 575 keV
/run/baemOn 10

/gun/energy 576 keV
/run/baemOn 10

/gun/energy 577 keV
/run/baemOn 10

/gun/energy 578 keV
/run/baemOn 10

/gun/energy 579 keV
/run/baemOn 10

/gun/energy 580 keV
/run/baemOn 10

/gun/energy 581 keV
/run/baemOn 10

/gun/energy 582 keV
/run/baemOn 10

/gun/energy 583 keV
/run/baemOn 10

/gun/energy 584 keV
/run/baemOn 10

/gun/energy 585 keV
/run/baemOn 10

/gun/energy 586 keV
/run/baemOn 10

/gun/energy 587 keV
/run/baemOn 10

/gun/energy 588 keV
/run/baemOn 10

/gun/energy 589 keV
/run/baemOn 10

/gun/energy 590 keV
/run/baemOn 10

/gun/energy 591 keV
/run/baemOn 10

/gun/energy 592 keV
/run/baemOn 10

/gun/energy 593 keV
/run/baemOn 10

/gun/energy 594 keV
/run/baemOn 10

/gun/energy 595 keV
/run/baemOn 10

/gun/energy 596 keV
/run/baemOn 10

/gun/energy 597 keV
/run/baemOn 10

/gun/energy 598 keV
/run/baemOn 10

/gun/energy 599 keV
/run/baemOn 10

/gun/energy 600 keV
/run/baemOn 10

/gun/energy 601 keV
/run/baemOn 10

/gun/energy 602 keV
/run/baemOn 10

/gun/energy 603 keV
/run/baemOn 10

/gun/energy 604 keV
/run/baemOn 10

/gun/energy 605 keV
/run/baemOn 10

/gun/energy 606 keV
/run/baemOn 10

/gun/energy 607 keV
/run/baemOn 10

/gun/energy 608 keV
/run/baemOn 10

/gun/energy 609 keV
/run/baemOn 10

/gun/energy 610 keV
/run/baemOn 10

/gun/energy 611 keV
/run/baemOn 10

/gun/energy 612 keV
/run/baemOn 10

/gun/energy 613 keV
/run/baemOn 10

/gun/energy 614 keV
/run/baemOn 10

/gun/energy 615 keV
/run/baemOn 10

/gun/energy 616 keV
/run/baemOn 10

/gun/energy 617 keV
/run/baemOn 10

/gun/energy 618 keV
/run/baemOn 10

/gun/energy 619 keV
/run/baemOn 10

/gun/energy 620 keV
/run/baemOn 10

/gun/energy 621 keV
/run/baemOn 10

/gun/energy 622 keV
/run/baemOn 10

/gun/energy 623 keV
/run/baemOn 10

/gun/energy 624 keV
/run/baemOn 10

/gun/energy 625 keV
/run/baemOn 10

/gun/energy 626 keV
/run/baemOn 10

/gun/energy 627 keV
/run/baemOn 10

/gun/energy 628 keV
/run/baemOn 10

/gun/energy 629 keV
/run/baemOn 10

/gun/energy 630 keV
/run/baemOn 10

/gun/energy 631 keV
/run/baemOn 10

/gun/energy 632 keV
/run/baemOn 10

/gun/energy 633 keV
/run/baemOn 10

/gun/energy 634 keV
/run/baemOn 10

/gun/energy 635 keV
/run/baemOn 10

/gun/energy 636 keV
/run/baemOn 10

/gun/energy 637 keV
/run/baemOn 10

/gun/energy 638 keV
/run/baemOn 10

/gun/energy 639 keV
/run/baemOn 10

/gun/energy 640 keV
/run/baemOn 10

/gun/energy 641 keV
/run/baemOn 10

/gun/energy 642 keV
/run/baemOn 10

/gun/energy 643 keV
/run/baemOn 10

/gun/energy 644 keV
/run/baemOn 10

/gun/energy 645 keV
/run/baemOn 10

/gun/energy 646 keV
/run/baemOn 10

/gun/energy 647 keV
/run/baemOn 10

/gun/energy 648 keV
/run/baemOn 10

/gun/energy 649 keV
/run/baemOn 10

/gun/energy 650 keV
/run/baemOn 10

/gun/energy 651 keV
/run/baemOn 10

/gun/energy 652 keV
/run/baemOn 10

/gun/energy 653 keV
/run/baemOn 10

/gun/energy 654 keV
/run/baemOn 10

/gun/energy 655 keV
/run/baemOn 10

/gun/energy 656 keV
/run/baemOn 10

/gun/energy 657 keV
/run/baemOn 10

/gun/energy 658 keV
/run/baemOn 10

/gun/energy 659 keV
/run/baemOn 10

/gun/energy 660 keV
/run/baemOn 10

/gun/energy 661 keV
/run/baemOn 10

/gun/energy 662 keV
/run/baemOn 10

/gun/energy 663 keV
/run/baemOn 10

/gun/energy 664 keV
/run/baemOn 10

/gun/energy 665 keV
/run/baemOn 10

/gun/energy 666 keV
/run/baemOn 10

/gun/energy 667 keV
/run/baemOn 10

/gun/energy 668 keV
/run/baemOn 10

/gun/energy 669 keV
/run/baemOn 10

/gun/energy 670 keV
/run/baemOn 10

/gun/energy 671 keV
/run/baemOn 10

/gun/energy 672 keV
/run/baemOn 10

/gun/energy 673 keV
/run/baemOn 10

/gun/energy 674 keV
/run/baemOn 10

/gun/energy 675 keV
/run/baemOn 10

/gun/energy 676 keV
/run/baemOn 10

/gun/energy 677 keV
/run/baemOn 10

/gun/energy 678 keV
/run/baemOn 10

/gun/energy 679 keV
/run/baemOn 10

/gun/energy 680 keV
/run/baemOn 10

/gun/energy 681 keV
/run/baemOn 10

/gun/energy 682 keV
/run/baemOn 10

/gun/energy 683 keV
/run/baemOn 10

/gun/energy 684 keV
/run/baemOn 10

/gun/energy 685 keV
/run/baemOn 10

/gun/energy 686 keV
/run/baemOn 10

/gun/energy 687 keV
/run/baemOn 10

/gun/energy 688 keV
/run/baemOn 10

/gun/energy 689 keV
/run/baemOn 10

/gun/energy 690 keV
/run/baemOn 10

/gun/energy 691 keV
/run/baemOn 10

/gun/energy 692 keV
/run/baemOn 10

/gun/energy 693 keV
/run/baemOn 10

/gun/energy 694 keV
/run/baemOn 10

/gun/energy 695 keV
/run/baemOn 10

/gun/energy 696 keV
/run/baemOn 10

/gun/energy 697 keV
/run/baemOn 10

/gun/energy 698 keV
/run/baemOn 10

/gun/energy 699 keV
/run/baemOn 10

/gun/energy 700 keV
/run/baemOn 10

/gun/energy 701 keV
/run/baemOn 10

/gun/energy 702 keV
/run/baemOn 10

/gun/energy 703 keV
/run/baemOn 10

/gun/energy 704 keV
/run/baemOn 10

/gun/energy 705 keV
/run/baemOn 10

/gun/energy 706 keV
/run/baemOn 10

/gun/energy 707 keV
/run/baemOn 10

/gun/energy 708 keV
/run/baemOn 10

/gun/energy 709 keV
/run/baemOn 10

/gun/energy 710 keV
/run/baemOn 10

/gun/energy 711 keV
/run/baemOn 10

/gun/energy 712 keV
/run/baemOn 10

/gun/energy 713 keV
/run/baemOn 10

/gun/energy 714 keV
/run/baemOn 10

/gun/energy 715 keV
/run/baemOn 10

/gun/energy 716 keV
/run/baemOn 10

/gun/energy 717 keV
/run/baemOn 10

/gun/energy 718 keV
/run/baemOn 10

/gun/energy 719 keV
/run/baemOn 10

/gun/energy 720 keV
/run/baemOn 10

/gun/energy 721 keV
/run/baemOn 10

/gun/energy 722 keV
/run/baemOn 10

/gun/energy 723 keV
/run/baemOn 10

/gun/energy 724 keV
/run/baemOn 10

/gun/energy 725 keV
/run/baemOn 10

/gun/energy 726 keV
/run/baemOn 10

/gun/energy 727 keV
/run/baemOn 10

/gun/energy 728 keV
/run/baemOn 10

/gun/energy 729 keV
/run/baemOn 10

/gun/energy 730 keV
/run/baemOn 10

/gun/energy 731 keV
/run/baemOn 10

/gun/energy 732 keV
/run/baemOn 10

/gun/energy 733 keV
/run/baemOn 10

/gun/energy 734 keV
/run/baemOn 10

/gun/energy 735 keV
/run/baemOn 10

/gun/energy 736 keV
/run/baemOn 10

/gun/energy 737 keV
/run/baemOn 10

/gun/energy 738 keV
/run/baemOn 10

/gun/energy 739 keV
/run/baemOn 10

/gun/energy 740 keV
/run/baemOn 10

/gun/energy 741 keV
/run/baemOn 10

/gun/energy 742 keV
/run/baemOn 10

/gun/energy 743 keV
/run/baemOn 10

/gun/energy 744 keV
/run/baemOn 10

/gun/energy 745 keV
/run/baemOn 10

/gun/energy 746 keV
/run/baemOn 10

/gun/energy 747 keV
/run/baemOn 10

/gun/energy 748 keV
/run/baemOn 10

/gun/energy 749 keV
/run/baemOn 10

/gun/energy 750 keV
/run/baemOn 10

/gun/energy 751 keV
/run/baemOn 10

/gun/energy 752 keV
/run/baemOn 10

/gun/energy 753 keV
/run/baemOn 10

/gun/energy 754 keV
/run/baemOn 10

/gun/energy 755 keV
/run/baemOn 10

/gun/energy 756 keV
/run/baemOn 10

/gun/energy 757 keV
/run/baemOn 10

/gun/energy 758 keV
/run/baemOn 10

/gun/energy 759 keV
/run/baemOn 10

/gun/energy 760 keV
/run/baemOn 10

/gun/energy 761 keV
/run/baemOn 10

/gun/energy 762 keV
/run/baemOn 10

/gun/energy 763 keV
/run/baemOn 10

/gun/energy 764 keV
/run/baemOn 10

/gun/energy 765 keV
/run/baemOn 10

/gun/energy 766 keV
/run/baemOn 10

/gun/energy 767 keV
/run/baemOn 10

/gun/energy 768 keV
/run/baemOn 10

/gun/energy 769 keV
/run/baemOn 10

/gun/energy 770 keV
/run/baemOn 10

/gun/energy 771 keV
/run/baemOn 10

/gun/energy 772 keV
/run/baemOn 10

/gun/energy 773 keV
/run/baemOn 10

/gun/energy 774 keV
/run/baemOn 10

/gun/energy 775 keV
/run/baemOn 10

/gun/energy 776 keV
/run/baemOn 10

/gun/energy 777 keV
/run/baemOn 10

/gun/energy 778 keV
/run/baemOn 10

/gun/energy 779 keV
/run/baemOn 10

/gun/energy 780 keV
/run/baemOn 10

/gun/energy 781 keV
/run/baemOn 10

/gun/energy 782 keV
/run/baemOn 10

/gun/energy 783 keV
/run/baemOn 10

/gun/energy 784 keV
/run/baemOn 10

/gun/energy 785 keV
/run/baemOn 10

/gun/energy 786 keV
/run/baemOn 10

/gun/energy 787 keV
/run/baemOn 10

/gun/energy 788 keV
/run/baemOn 10

/gun/energy 789 keV
/run/baemOn 10

/gun/energy 790 keV
/run/baemOn 10

/gun/energy 791 keV
/run/baemOn 10

/gun/energy 792 keV
/run/baemOn 10

/gun/energy 793 keV
/run/baemOn 10

/gun/energy 794 keV
/run/baemOn 10

/gun/energy 795 keV
/run/baemOn 10

/gun/energy 796 keV
/run/baemOn 10

/gun/energy 797 keV
/run/baemOn 10

/gun/energy 798 keV
/run/baemOn 10

/gun/energy 799 keV
/run/baemOn 10

/gun/energy 800 keV
/run/baemOn 10

/gun/energy 801 keV
/run/baemOn 10

/gun/energy 802 keV
/run/baemOn 10

/gun/energy 803 keV
/run/baemOn 10

/gun/energy 804 keV
/run/baemOn 10

/gun/energy 805 keV
/run/baemOn 10

/gun/energy 806 keV
/run/baemOn 10

/gun/energy 807 keV
/run/baemOn 10

/gun/energy 808 keV
/run/baemOn 10

/gun/energy 809 keV
/run/baemOn 10

/gun/energy 810 keV
/run/baemOn 10

/gun/energy 811 keV
/run/baemOn 10

/gun/energy 812 keV
/run/baemOn 10

/gun/energy 813 keV
/run/baemOn 10

/gun/energy 814 keV
/run/baemOn 10

/gun/energy 815 keV
/run/baemOn 10

/gun/energy 816 keV
/run/baemOn 10

/gun/energy 817 keV
/run/baemOn 10

/gun/energy 818 keV
/run/baemOn 10

/gun/energy 819 keV
/run/baemOn 10

/gun/energy 820 keV
/run/baemOn 10

/gun/energy 821 keV
/run/baemOn 10

/gun/energy 822 keV
/run/baemOn 10

/gun/energy 823 keV
/run/baemOn 10

/gun/energy 824 keV
/run/baemOn 10

/gun/energy 825 keV
/run/baemOn 10

/gun/energy 826 keV
/run/baemOn 10

/gun/energy 827 keV
/run/baemOn 10

/gun/energy 828 keV
/run/baemOn 10

/gun/energy 829 keV
/run/baemOn 10

/gun/energy 830 keV
/run/baemOn 10

/gun/energy 831 keV
/run/baemOn 10

/gun/energy 832 keV
/run/baemOn 10

/gun/energy 833 keV
/run/baemOn 10

/gun/energy 834 keV
/run/baemOn 10

/gun/energy 835 keV
/run/baemOn 10

/gun/energy 836 keV
/run/baemOn 10

/gun/energy 837 keV
/run/baemOn 10

/gun/energy 838 keV
/run/baemOn 10

/gun/energy 839 keV
/run/baemOn 10

/gun/energy 840 keV
/run/baemOn 10

/gun/energy 841 keV
/run/baemOn 10

/gun/energy 842 keV
/run/baemOn 10

/gun/energy 843 keV
/run/baemOn 10

/gun/energy 844 keV
/run/baemOn 10

/gun/energy 845 keV
/run/baemOn 10

/gun/energy 846 keV
/run/baemOn 10

/gun/energy 847 keV
/run/baemOn 10

/gun/energy 848 keV
/run/baemOn 10

/gun/energy 849 keV
/run/baemOn 10

/gun/energy 850 keV
/run/baemOn 10

/gun/energy 851 keV
/run/baemOn 10

/gun/energy 852 keV
/run/baemOn 10

/gun/energy 853 keV
/run/baemOn 10

/gun/energy 854 keV
/run/baemOn 10

/gun/energy 855 keV
/run/baemOn 10

/gun/energy 856 keV
/run/baemOn 10

/gun/energy 857 keV
/run/baemOn 10

/gun/energy 858 keV
/run/baemOn 10

/gun/energy 859 keV
/run/baemOn 10

/gun/energy 860 keV
/run/baemOn 10

/gun/energy 861 keV
/run/baemOn 10

/gun/energy 862 keV
/run/baemOn 10

/gun/energy 863 keV
/run/baemOn 10

/gun/energy 864 keV
/run/baemOn 10

/gun/energy 865 keV
/run/baemOn 10

/gun/energy 866 keV
/run/baemOn 10

/gun/energy 867 keV
/run/baemOn 10

/gun/energy 868 keV
/run/baemOn 10

/gun/energy 869 keV
/run/baemOn 10

/gun/energy 870 keV
/run/baemOn 10

/gun/energy 871 keV
/run/baemOn 10

/gun/energy 872 keV
/run/baemOn 10

/gun/energy 873 keV
/run/baemOn 10

/gun/energy 874 keV
/run/baemOn 10

/gun/energy 875 keV
/run/baemOn 10

/gun/energy 876 keV
/run/baemOn 10

/gun/energy 877 keV
/run/baemOn 10

/gun/energy 878 keV
/run/baemOn 10

/gun/energy 879 keV
/run/baemOn 10

/gun/energy 880 keV
/run/baemOn 10

/gun/energy 881 keV
/run/baemOn 10

/gun/energy 882 keV
/run/baemOn 10

/gun/energy 883 keV
/run/baemOn 10

/gun/energy 884 keV
/run/baemOn 10

/gun/energy 885 keV
/run/baemOn 10

/gun/energy 886 keV
/run/baemOn 10

/gun/energy 887 keV
/run/baemOn 10

/gun/energy 888 keV
/run/baemOn 10

/gun/energy 889 keV
/run/baemOn 10

/gun/energy 890 keV
/run/baemOn 10

/gun/energy 891 keV
/run/baemOn 10

/gun/energy 892 keV
/run/baemOn 10

/gun/energy 893 keV
/run/baemOn 10

/gun/energy 894 keV
/run/baemOn 10

/gun/energy 895 keV
/run/baemOn 10

/gun/energy 896 keV
/run/baemOn 10

/gun/energy 897 keV
/run/baemOn 10

/gun/energy 898 keV
/run/baemOn 10

/gun/energy 899 keV
/run/baemOn 10

/gun/energy 900 keV
/run/baemOn 10

/gun/energy 901 keV
/run/baemOn 10

/gun/energy 902 keV
/run/baemOn 10

/gun/energy 903 keV
/run/baemOn 10

/gun/energy 904 keV
/run/baemOn 10

/gun/energy 905 keV
/run/baemOn 10

/gun/energy 906 keV
/run/baemOn 10

/gun/energy 907 keV
/run/baemOn 10

/gun/energy 908 keV
/run/baemOn 10

/gun/energy 909 keV
/run/baemOn 10

/gun/energy 910 keV
/run/baemOn 10

/gun/energy 911 keV
/run/baemOn 10

/gun/energy 912 keV
/run/baemOn 10

/gun/energy 913 keV
/run/baemOn 10

/gun/energy 914 keV
/run/baemOn 10

/gun/energy 915 keV
/run/baemOn 10

/gun/energy 916 keV
/run/baemOn 10

/gun/energy 917 keV
/run/baemOn 10

/gun/energy 918 keV
/run/baemOn 10

/gun/energy 919 keV
/run/baemOn 10

/gun/energy 920 keV
/run/baemOn 10

/gun/energy 921 keV
/run/baemOn 10

/gun/energy 922 keV
/run/baemOn 10

/gun/energy 923 keV
/run/baemOn 10

/gun/energy 924 keV
/run/baemOn 10

/gun/energy 925 keV
/run/baemOn 10

/gun/energy 926 keV
/run/baemOn 10

/gun/energy 927 keV
/run/baemOn 10

/gun/energy 928 keV
/run/baemOn 10

/gun/energy 929 keV
/run/baemOn 10

/gun/energy 930 keV
/run/baemOn 10

/gun/energy 931 keV
/run/baemOn 10

/gun/energy 932 keV
/run/baemOn 10

/gun/energy 933 keV
/run/baemOn 10

/gun/energy 934 keV
/run/baemOn 10

/gun/energy 935 keV
/run/baemOn 10

/gun/energy 936 keV
/run/baemOn 10

/gun/energy 937 keV
/run/baemOn 10

/gun/energy 938 keV
/run/baemOn 10

/gun/energy 939 keV
/run/baemOn 10

/gun/energy 940 keV
/run/baemOn 10

/gun/energy 941 keV
/run/baemOn 10

/gun/energy 942 keV
/run/baemOn 10

/gun/energy 943 keV
/run/baemOn 10

/gun/energy 944 keV
/run/baemOn 10

/gun/energy 945 keV
/run/baemOn 10

/gun/energy 946 keV
/run/baemOn 10

/gun/energy 947 keV
/run/baemOn 10

/gun/energy 948 keV
/run/baemOn 10

/gun/energy 949 keV
/run/baemOn 10

/gun/energy 950 keV
/run/baemOn 10

/gun/energy 951 keV
/run/baemOn 10

/gun/energy 952 keV
/run/baemOn 10

/gun/energy 953 keV
/run/baemOn 10

/gun/energy 954 keV
/run/baemOn 10

/gun/energy 955 keV
/run/baemOn 10

/gun/energy 956 keV
/run/baemOn 10

/gun/energy 957 keV
/run/baemOn 10

/gun/energy 958 keV
/run/baemOn 10

/gun/energy 959 keV
/run/baemOn 10

/gun/energy 960 keV
/run/baemOn 10

/gun/energy 961 keV
/run/baemOn 10

/gun/energy 962 keV
/run/baemOn 10

/gun/energy 963 keV
/run/baemOn 10

/gun/energy 964 keV
/run/baemOn 10

/gun/energy 965 keV
/run/baemOn 10

/gun/energy 966 keV
/run/baemOn 10

/gun/energy 967 keV
/run/baemOn 10

/gun/energy 968 keV
/run/baemOn 10

/gun/energy 969 keV
/run/baemOn 10

/gun/energy 970 keV
/run/baemOn 10

/gun/energy 971 keV
/run/baemOn 10

/gun/energy 972 keV
/run/baemOn 10

/gun/energy 973 keV
/run/baemOn 10

/gun/energy 974 keV
/run/baemOn 10

/gun/energy 975 keV
/run/baemOn 10

/gun/energy 976 keV
/run/baemOn 10

/gun/energy 977 keV
/run/baemOn 10

/gun/energy 978 keV
/run/baemOn 10

/gun/energy 979 keV
/run/baemOn 10

/gun/energy 980 keV
/run/baemOn 10

/gun/energy 981 keV
/run/baemOn 10

/gun/energy 982 keV
/run/baemOn 10

/gun/energy 983 keV
/run/baemOn 10

/gun/energy 984 keV
/run/baemOn 10

/gun/energy 985 keV
/run/baemOn 10

/gun/energy 986 keV
/run/baemOn 10

/gun/energy 987 keV
/run/baemOn 10

/gun/energy 988 keV
/run/baemOn 10

/gun/energy 989 keV
/run/baemOn 10

/gun/energy 990 keV
/run/baemOn 10

/gun/energy 991 keV
/run/baemOn 10

/gun/energy 992 keV
/run/baemOn 10

/gun/energy 993 keV
/run/baemOn 10

/gun/energy 994 keV
/run/baemOn 10

/gun/energy 995 keV
/run/baemOn 10

/gun/energy 996 keV
/run/baemOn 10

/gun/energy 997 keV
/run/baemOn 10

/gun/energy 998 keV
/run/baemOn 10

/gun/energy 999 keV
/run/baemOn 10

/gun/energy 1000 keV
/run/baemOn 10

/gun/energy 1001 keV
/run/baemOn 10

/gun/energy 1002 keV
/run/baemOn 10

/gun/energy 1003 keV
/run/baemOn 10

/gun/energy 1004 keV
/run/baemOn 10

/gun/energy 1005 keV
/run/baemOn 10

/gun/energy 1006 keV
/run/baemOn 10

/gun/energy 1007 keV
/run/baemOn 10

/gun/energy 1008 keV
/run/baemOn 10

/gun/energy 1009 keV
/run/baemOn 10

/gun/energy 1010 keV
/run/baemOn 10

/gun/energy 1011 keV
/run/baemOn 10

/gun/energy 1012 keV
/run/baemOn 10

/gun/energy 1013 keV
/run/baemOn 10

/gun/energy 1014 keV
/run/baemOn 10

/gun/energy 1015 keV
/run/baemOn 10

/gun/energy 1016 keV
/run/baemOn 10

/gun/energy 1017 keV
/run/baemOn 10

/gun/energy 1018 keV
/run/baemOn 10

/gun/energy 1019 keV
/run/baemOn 10

/gun/energy 1020 keV
/run/baemOn 10

/gun/energy 1021 keV
/run/baemOn 10

/gun/energy 1022 keV
/run/baemOn 10

/gun/energy 1023 keV
/run/baemOn 10

/gun/energy 1024 keV
/run/baemOn 10

/gun/energy 1025 keV
/run/baemOn 10

/gun/energy 1026 keV
/run/baemOn 10

/gun/energy 1027 keV
/run/baemOn 10

/gun/energy 1028 keV
/run/baemOn 10

/gun/energy 1029 keV
/run/baemOn 10

/gun/energy 1030 keV
/run/baemOn 10

/gun/energy 1031 keV
/run/baemOn 10

/gun/energy 1032 keV
/run/baemOn 10

/gun/energy 1033 keV
/run/baemOn 10

/gun/energy 1034 keV
/run/baemOn 10

/gun/energy 1035 keV
/run/baemOn 10

/gun/energy 1036 keV
/run/baemOn 10

/gun/energy 1037 keV
/run/baemOn 10

/gun/energy 1038 keV
/run/baemOn 10

/gun/energy 1039 keV
/run/baemOn 10

/gun/energy 1040 keV
/run/baemOn 10

/gun/energy 1041 keV
/run/baemOn 10

/gun/energy 1042 keV
/run/baemOn 10

/gun/energy 1043 keV
/run/baemOn 10

/gun/energy 1044 keV
/run/baemOn 10

/gun/energy 1045 keV
/run/baemOn 10

/gun/energy 1046 keV
/run/baemOn 10

/gun/energy 1047 keV
/run/baemOn 10

/gun/energy 1048 keV
/run/baemOn 10

/gun/energy 1049 keV
/run/baemOn 10

/gun/energy 1050 keV
/run/baemOn 10

/gun/energy 1051 keV
/run/baemOn 10

/gun/energy 1052 keV
/run/baemOn 10

/gun/energy 1053 keV
/run/baemOn 10

/gun/energy 1054 keV
/run/baemOn 10

/gun/energy 1055 keV
/run/baemOn 10

/gun/energy 1056 keV
/run/baemOn 10

/gun/energy 1057 keV
/run/baemOn 10

/gun/energy 1058 keV
/run/baemOn 10

/gun/energy 1059 keV
/run/baemOn 10

/gun/energy 1060 keV
/run/baemOn 10

/gun/energy 1061 keV
/run/baemOn 10

/gun/energy 1062 keV
/run/baemOn 10

/gun/energy 1063 keV
/run/baemOn 10

/gun/energy 1064 keV
/run/baemOn 10

/gun/energy 1065 keV
/run/baemOn 10

/gun/energy 1066 keV
/run/baemOn 10

/gun/energy 1067 keV
/run/baemOn 10

/gun/energy 1068 keV
/run/baemOn 10

/gun/energy 1069 keV
/run/baemOn 10

/gun/energy 1070 keV
/run/baemOn 10

/gun/energy 1071 keV
/run/baemOn 10

/gun/energy 1072 keV
/run/baemOn 10

/gun/energy 1073 keV
/run/baemOn 10

/gun/energy 1074 keV
/run/baemOn 10

/gun/energy 1075 keV
/run/baemOn 10

/gun/energy 1076 keV
/run/baemOn 10

/gun/energy 1077 keV
/run/baemOn 10

/gun/energy 1078 keV
/run/baemOn 10

/gun/energy 1079 keV
/run/baemOn 10

/gun/energy 1080 keV
/run/baemOn 10

/gun/energy 1081 keV
/run/baemOn 10

/gun/energy 1082 keV
/run/baemOn 10

/gun/energy 1083 keV
/run/baemOn 10

/gun/energy 1084 keV
/run/baemOn 10

/gun/energy 1085 keV
/run/baemOn 10

/gun/energy 1086 keV
/run/baemOn 10

/gun/energy 1087 keV
/run/baemOn 10

/gun/energy 1088 keV
/run/baemOn 10

/gun/energy 1089 keV
/run/baemOn 10

/gun/energy 1090 keV
/run/baemOn 10

/gun/energy 1091 keV
/run/baemOn 10

/gun/energy 1092 keV
/run/baemOn 10

/gun/energy 1093 keV
/run/baemOn 10

/gun/energy 1094 keV
/run/baemOn 10

/gun/energy 1095 keV
/run/baemOn 10

/gun/energy 1096 keV
/run/baemOn 10

/gun/energy 1097 keV
/run/baemOn 10

/gun/energy 1098 keV
/run/baemOn 10

/gun/energy 1099 keV
/run/baemOn 10

/gun/energy 1100 keV
/run/baemOn 10

/gun/energy 1101 keV
/run/baemOn 10

/gun/energy 1102 keV
/run/baemOn 10

/gun/energy 1103 keV
/run/baemOn 10

/gun/energy 1104 keV
/run/baemOn 10

/gun/energy 1105 keV
/run/baemOn 10

/gun/energy 1106 keV
/run/baemOn 10

/gun/energy 1107 keV
/run/baemOn 10

/gun/energy 1108 keV
/run/baemOn 10

/gun/energy 1109 keV
/run/baemOn 10

/gun/energy 1110 keV
/run/baemOn 10

/gun/energy 1111 keV
/run/baemOn 10

/gun/energy 1112 keV
/run/baemOn 10

/gun/energy 1113 keV
/run/baemOn 10

/gun/energy 1114 keV
/run/baemOn 10

/gun/energy 1115 keV
/run/baemOn 10

/gun/energy 1116 keV
/run/baemOn 10

/gun/energy 1117 keV
/run/baemOn 10

/gun/energy 1118 keV
/run/baemOn 10

/gun/energy 1119 keV
/run/baemOn 10

/gun/energy 1120 keV
/run/baemOn 10

/gun/energy 1121 keV
/run/baemOn 10

/gun/energy 1122 keV
/run/baemOn 10

/gun/energy 1123 keV
/run/baemOn 10

/gun/energy 1124 keV
/run/baemOn 10

/gun/energy 1125 keV
/run/baemOn 10

/gun/energy 1126 keV
/run/baemOn 10

/gun/energy 1127 keV
/run/baemOn 10

/gun/energy 1128 keV
/run/baemOn 10

/gun/energy 1129 keV
/run/baemOn 10

/gun/energy 1130 keV
/run/baemOn 10

/gun/energy 1131 keV
/run/baemOn 10

/gun/energy 1132 keV
/run/baemOn 10

/gun/energy 1133 keV
/run/baemOn 10

/gun/energy 1134 keV
/run/baemOn 10

/gun/energy 1135 keV
/run/baemOn 10

/gun/energy 1136 keV
/run/baemOn 10

/gun/energy 1137 keV
/run/baemOn 10

/gun/energy 1138 keV
/run/baemOn 10

/gun/energy 1139 keV
/run/baemOn 10

/gun/energy 1140 keV
/run/baemOn 10

/gun/energy 1141 keV
/run/baemOn 10

/gun/energy 1142 keV
/run/baemOn 10

/gun/energy 1143 keV
/run/baemOn 10

/gun/energy 1144 keV
/run/baemOn 10

/gun/energy 1145 keV
/run/baemOn 10

/gun/energy 1146 keV
/run/baemOn 10

/gun/energy 1147 keV
/run/baemOn 10

/gun/energy 1148 keV
/run/baemOn 10

/gun/energy 1149 keV
/run/baemOn 10

/gun/energy 1150 keV
/run/baemOn 10

/gun/energy 1151 keV
/run/baemOn 10

/gun/energy 1152 keV
/run/baemOn 10

/gun/energy 1153 keV
/run/baemOn 10

/gun/energy 1154 keV
/run/baemOn 10

/gun/energy 1155 keV
/run/baemOn 10

/gun/energy 1156 keV
/run/baemOn 10

/gun/energy 1157 keV
/run/baemOn 10

/gun/energy 1158 keV
/run/baemOn 10

/gun/energy 1159 keV
/run/baemOn 10

/gun/energy 1160 keV
/run/baemOn 10

/gun/energy 1161 keV
/run/baemOn 10

/gun/energy 1162 keV
/run/baemOn 10

/gun/energy 1163 keV
/run/baemOn 10

/gun/energy 1164 keV
/run/baemOn 10

/gun/energy 1165 keV
/run/baemOn 10

/gun/energy 1166 keV
/run/baemOn 10

/gun/energy 1167 keV
/run/baemOn 10

/gun/energy 1168 keV
/run/baemOn 10

/gun/energy 1169 keV
/run/baemOn 10

/gun/energy 1170 keV
/run/baemOn 10

/gun/energy 1171 keV
/run/baemOn 10

/gun/energy 1172 keV
/run/baemOn 10

/gun/energy 1173 keV
/run/baemOn 10

/gun/energy 1174 keV
/run/baemOn 10

/gun/energy 1175 keV
/run/baemOn 10

/gun/energy 1176 keV
/run/baemOn 10

/gun/energy 1177 keV
/run/baemOn 10

/gun/energy 1178 keV
/run/baemOn 10

/gun/energy 1179 keV
/run/baemOn 10

/gun/energy 1180 keV
/run/baemOn 10

/gun/energy 1181 keV
/run/baemOn 10

/gun/energy 1182 keV
/run/baemOn 10

/gun/energy 1183 keV
/run/baemOn 10

/gun/energy 1184 keV
/run/baemOn 10

/gun/energy 1185 keV
/run/baemOn 10

/gun/energy 1186 keV
/run/baemOn 10

/gun/energy 1187 keV
/run/baemOn 10

/gun/energy 1188 keV
/run/baemOn 10

/gun/energy 1189 keV
/run/baemOn 10

/gun/energy 1190 keV
/run/baemOn 10

/gun/energy 1191 keV
/run/baemOn 10

/gun/energy 1192 keV
/run/baemOn 10

/gun/energy 1193 keV
/run/baemOn 10

/gun/energy 1194 keV
/run/baemOn 10

/gun/energy 1195 keV
/run/baemOn 10

/gun/energy 1196 keV
/run/baemOn 10

/gun/energy 1197 keV
/run/baemOn 10

/gun/energy 1198 keV
/run/baemOn 10

/gun/energy 1199 keV
/run/baemOn 10